/**
 * Hissab — PDF report generator
 * Requires jsPDF (loaded via CDN in reports.php) — produces a real
 * text-based PDF (not a screenshot) from the report data passed in.
 *
 * Usage: downloadHissabReportPDF(reportDataObject)
 * See reports.php for the shape of reportDataObject.
 */
function downloadHissabReportPDF(data) {
  var jsPDFCtor = window.jspdf.jsPDF;
  var doc = new jsPDFCtor({ unit: 'pt', format: 'a4' });
  var pageWidth = doc.internal.pageSize.getWidth();
  var pageHeight = doc.internal.pageSize.getHeight();
  var marginX = 44;
  var y = 56;

  function checkPageBreak(nextLineHeight) {
    if (y + nextLineHeight > pageHeight - 50) {
      doc.addPage();
      y = 56;
    }
  }

  // ---- Header ----
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(21, 115, 71);
  doc.text('Hissab', marginX, y);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  doc.setTextColor(100, 100, 100);
  doc.text('Sustainable Finance System — Financial Report', marginX, y + 16);

  y += 38;
  doc.setDrawColor(224, 228, 226);
  doc.line(marginX, y, pageWidth - marginX, y);
  y += 24;

  // ---- Meta info ----
  doc.setFontSize(10.5);
  doc.setTextColor(60, 60, 60);
  doc.text('Account: ' + data.userName + ' (' + data.userEmail + ')', marginX, y);
  y += 16;
  doc.text('Report period: ' + data.monthLabel, marginX, y);
  y += 16;
  doc.text('Generated on: ' + data.generatedOn, marginX, y);
  y += 32;

  // ---- Summary boxes ----
  var gap = 12;
  var boxW = (pageWidth - marginX * 2 - gap * 2) / 3;
  var boxes = [
    { label: 'TOTAL INCOME', value: data.currency + ' ' + data.totalIncome, color: [21, 115, 71] },
    { label: 'TOTAL EXPENSES', value: data.currency + ' ' + data.totalExpense, color: [220, 38, 38] },
    { label: 'NET BALANCE', value: data.currency + ' ' + data.netBalance, color: [16, 24, 40] }
  ];
  boxes.forEach(function (b, i) {
    var x = marginX + i * (boxW + gap);
    doc.setDrawColor(230, 232, 231);
    doc.setFillColor(247, 249, 248);
    doc.roundedRect(x, y, boxW, 58, 6, 6, 'FD');
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(120, 120, 120);
    doc.text(b.label, x + 12, y + 20);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13.5);
    doc.setTextColor(b.color[0], b.color[1], b.color[2]);
    doc.text(b.value, x + 12, y + 41);
  });
  y += 82;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10.5);
  doc.setTextColor(60, 60, 60);
  doc.text('Savings rate this period: ' + data.savingsRate + '%', marginX, y);
  y += 30;

  // ---- Category table section ----
  function drawCategoryTable(title, rows, accentColor) {
    checkPageBreak(50);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12.5);
    doc.setTextColor(20, 20, 20);
    doc.text(title, marginX, y);
    y += 10;
    doc.setDrawColor(230, 232, 231);
    doc.line(marginX, y, pageWidth - marginX, y);
    y += 20;

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10.5);

    if (!rows.length) {
      doc.setTextColor(150, 150, 150);
      doc.text('No entries for this period.', marginX, y);
      y += 26;
      return;
    }

    rows.forEach(function (r) {
      checkPageBreak(18);
      doc.setTextColor(70, 70, 70);
      doc.text(r.name, marginX, y);
      doc.setTextColor(accentColor[0], accentColor[1], accentColor[2]);
      doc.text(data.currency + ' ' + r.total, pageWidth - marginX, y, { align: 'right' });
      y += 18;
    });
    y += 18;
  }

  drawCategoryTable('Income by Category', data.incomeRows, [21, 115, 71]);
  drawCategoryTable('Expenses by Category', data.expenseRows, [220, 38, 38]);

  // ---- Footer page numbers ----
  var pageCount = doc.internal.getNumberOfPages();
  for (var p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.setTextColor(160, 160, 160);
    doc.text('Hissab · Page ' + p + ' of ' + pageCount, marginX, pageHeight - 30);
    doc.text('Generated by Hissab — for personal record keeping', pageWidth - marginX, pageHeight - 30, { align: 'right' });
  }

  doc.save('Hissab-Report-' + data.monthValue + '.pdf');
}
